In [ ]:
import tensorflow as tf

In [2]:
def neuron(x, W, b):
    return tf.add(tf.matmul(W, x), b)


class Layer(tf.keras.layers.Layer):
    def __init__(self, n_units=5):
        super(Layer, self).__init__()

        self.n_units = n_units

    def build(self, input_shape):
        for i in range(self.n_units):
            exec(f'self.kernel_{i} = self.add_weight("kernel_{i}", shape=[1, int(input_shape[0])])')
            exec(f'self.bias_{i} = self.add_weight("bias_{i}", shape=[1, 1])')

    def call(self, inputs):
        for i in range(self.n_units):
            exec(f'out_{i} = neuron(inputs, self.kernel_{i}, self.bias_{i})')
        return eval(f'tf.concat([{", ".join([ f"out_{i}" for i in range(self.n_units) ])}], axis=0)')


# Check to see if it outputs the correct thing
layer = Layer(5) # With 5 neurons, it should return a (5, 6)
print(layer(tf.zeros([10, 6])))

# Check to see if it has the right trainable parameters
print(layer.trainable_variables)

# Check to see if TensorFlow can find the gradients
layer = Layer(5)
x = tf.ones([10, 6])
with tf.GradientTape() as tape:
    z = layer(x)
print(f"Parameter: {layer.trainable_variables[2]}")
print(f"Gradient:  {tape.gradient(z, layer.trainable_variables[2])}")




f:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.3)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "


tf.Tensor(
[[-1.3077018  -1.3077018  -1.3077018  -1.3077018  -1.3077018  -1.3077018 ]
 [-1.11112    -1.11112    -1.11112    -1.11112    -1.11112    -1.11112   ]
 [ 0.630515    0.630515    0.630515    0.630515    0.630515    0.630515  ]
 [-0.9860659  -0.9860659  -0.9860659  -0.9860659  -0.9860659  -0.9860659 ]
 [-0.37826955 -0.37826955 -0.37826955 -0.37826955 -0.37826955 -0.37826955]], shape=(5, 6), dtype=float32)
[<tf.Variable 'layer/kernel_0:0' shape=(1, 10) dtype=float32, numpy=
array([[-0.5181979 , -0.63445526,  0.71040076, -0.3345592 , -0.20917523,
         0.06701553, -0.55154145, -0.24975619, -0.47119582,  0.09324765]],
      dtype=float32)>, <tf.Variable 'layer/bias_0:0' shape=(1, 1) dtype=float32, numpy=array([[-1.3077018]], dtype=float32)>, <tf.Variable 'layer/kernel_1:0' shape=(1, 10) dtype=float32, numpy=
array([[-0.40697047, -0.35724512, -0.45898494,  0.39768225,  0.36645836,
        -0.17587161, -0.11867851,  0.05743659, -0.19261754,  0.5392751 ]],
      dtype=float32)>, <